### ISSUE TITLE
Could you plan to support upload images to qiniu?

### ISSUE THREAD

**Issue by zen-li** [lpreterite/vue-tinymce#1]
RT, thanks

**Comment by lpreterite** [comment]
不打算支持，因为七牛上传还得属于需求底层，图片传入可能是从已有图片选择，起码我目前这个项目是这样的，如果你需要使用到七牛上传可以关注这个[qiniu-uploader](https://github.com/lpreterite/qiniu-uploader)。至于图片插入的方法会考虑支持的：）
