### ISSUE TITLE
在代码中清空content内容不会跟着刷新

### ISSUE THREAD

**Issue by yousayyosoro** [lpreterite/vue-tinymce#12]
我在做提交后清空内容的时候发现清空不了得手动调setContent才行

**Comment by lpreterite** [comment]
请问你使用的是什么版本？具体怎样操作的？能不能在codepen提供一下例子？

**Comment by lpreterite** [comment]
> 我在做提交后清空内容的时候发现清空不了得手动调setContent才行

最近我这边也发现这个问题了，已在版本1.1.0修复。欢迎更新后继续使用，多谢你的反馈！
