### ISSUE TITLE
同个页面，如何加载多个tinymce编辑器？

### ISSUE THREAD

**Issue by samdebug** [lpreterite/vue-tinymce#13]
同个页面，如何加载多个tinymce编辑器？

**Comment by lpreterite** [comment]
> 同个页面，如何加载多个tinymce编辑器？

你好，请问是用我这个vue-tinymce插件时遇到的问题吗？为了方便调试问题能提供一下复现问题的例子吗？（比如提供[codepen的例子](https://codepen.io/packy1980/pen/BayPrVO)）

**Comment by samdebug** [comment]
就是我vue项目一个页面里面定义了两个`<vue-tinymce ref="tinymce" v-model="greet" :setting="setting" :setup="setup"></vue-tinymce>`，但是渲染后我发现只有一个vue-tinymce渲染成功了，请问是什么问题

**Comment by lpreterite** [comment]
> 就是我vue项目一个页面里面定义了两个`<vue-tinymce ref="tinymce" v-model="greet" :setting="setting" :setup="setup"></vue-tinymce>`，但是渲染后我发现只有一个vue-tinymce渲染成功了，请问是什么问题

在我上面那个codepen例子中试了一下，发现`<vue-tinymce />`这种标签写法不能直接用在HTML里，因为不规范导致解析HTML时判别他没有闭合，所以多`<vue-tinymce />`没有效果。只有经过vue-loader解析的情况下，才可以用`<vue-tinymce />`这种标签写法。

不知道你是不是这种情况，能提供例子可能会更快地解决问题。

**Comment by jamey997** [comment]
```
  <vue-tinymce
      ref="editor"
      class="editor"
      v-model="content"
      :setting="{inline: false}"
      :setup="setup"
      @keyup.native="$emit('editorChange', content)"
    />
```
在编辑器设置setting中的inline字段设置成false，就可以同在一个页面中加载多个tinymce编辑器
