### ISSUE TITLE
bug：content变化后，编辑器的content不更新

### ISSUE THREAD

**Issue by hello-lun** [lpreterite/vue-tinymce#16]
![image](https://user-images.githubusercontent.com/34638158/84009071-50e36800-a9a5-11ea-88e5-bbf3052fad4e.png)

bug示例如下图
![20200608_163325](https://user-images.githubusercontent.com/34638158/84009519-f5fe4080-a9a5-11ea-9a31-701eb3aa30c0.gif)

**Comment by lpreterite** [comment]
你好，我目前没有在当编辑的时候会发生文本内容需要实时更新的需求，而定位到问题当`status==INPUT`这个状态是为了回避双向绑定导致的编辑器二次刷新处理，我这边还没有找到更好的办法来处理，所以这个问题在最近应该暂时不会修复。

如果你非常急于处理这个问题，可能需要手动调起组件的editor对象通过`setContent()`方法主动更新文本内容。

**Comment by lpreterite** [comment]
这个问题已在版本1.1.1修复，可以用新版本改善你的情况。相关问题看 #27
