### ISSUE TITLE
是否会考虑当我导入富文本时，会自动将其转为文本

### ISSUE THREAD

**Issue by longletian** [lpreterite/vue-tinymce#19]

**Comment by lpreterite** [comment]
你好，我无法准确回答你的疑问。

单从你的标题我无法定位你问题的具体情况。

1. “当我导入富文本时”？我不是很清楚你导入两字背后具体操作是什么？
2. “会自动将其转为文本”？转为文本的意思是转成怎样的格式？像markdown哪样？图片又将转换为何种形式？不是很明白用意。
3. “是否会考虑”？tinymce是本vue插件的核心，所以你这个提议我建议应该去找tinymce团队问一下。

**Comment by longletian** [comment]
![Uploading image.png…]()

**Comment by longletian** [comment]
不支持code模式？ 
![image](https://user-images.githubusercontent.com/28197668/101653651-82371080-3a7a-11eb-9ded-b42ada5ba0be.png)
