### ISSUE TITLE
editor does not update value on bold/italic

### ISSUE THREAD

**Issue by werkzeugh** [lpreterite/vue-tinymce#2]
the editor does not update the bound variable when only formatting is changed.

to fix just add "ExecCommand" to the list of events you listen to:

` editor.on('input change undo redo ExecCommand' ...
`

**Comment by lpreterite** [comment]
The problem has been fixed, thanks for your feedback ヾ(ﾟ∀ﾟゞ)

**Comment by werkzeugh** [comment]
thanks
