### ISSUE TITLE
表格没有选中高亮的效果，和官网不一样？

### ISSUE THREAD

**Issue by G-WangZH** [lpreterite/vue-tinymce#45]
实际效果：
![image](https://user-images.githubusercontent.com/24827526/130556603-c9223001-7a34-40e2-aea9-ce87e73cdfeb.png)

预期效果：
![image](https://user-images.githubusercontent.com/24827526/130556644-30033395-d6e4-44af-87c8-1e61e9b391f3.png)

**Comment by lpreterite** [comment]
这个你得添加table插件来完善此功能。

**Comment by will961123** [comment]
use-import目录的使用示例代码遇到同样问题

**Comment by lpreterite** [comment]
> 使用use-import目录的示例代码遇到同样问题

这个你得在node_modules/tinymce/目录下找到table插件，通过`import`的方式引用进项目就能生效。
