### ISSUE TITLE
vue3的版本应该是vue.3.0.0+了吧

### ISSUE THREAD

**Issue by RSS1102** [lpreterite/vue-tinymce#52]
我看到项目的vue版本还停留在vue2.6上，能支持vue3吗？

**Comment by lpreterite** [comment]
> 我看到项目的vue版本还停留在vue2.6上，能支持vue3吗？

需要使用vue3版本的，按下面的方式安装就行：

```
npm i @packy-tang/vue-tinymce@next
```

对应分支在[2.0.0-beta.1](https://github.com/lpreterite/vue-tinymce/tree/2.0.0-beta.1)

**Comment by RSS1102** [comment]
这个分支可以通过连接达到，但是不能在分支列表查找到。
![image](https://user-images.githubusercontent.com/81673017/170176402-a7c93a04-abc1-40b4-91d3-a3ed88798d6e.png)
