### ISSUE TITLE
插件加载不成功

### ISSUE THREAD

**Issue by malaimoo** [lpreterite/vue-tinymce#6]
我的 setting 是这样的，使用了 vue 模板组件：
`       setting: Object.assign(TinymceSetting, {
          height: 200,
          block_formats: "Paragraph=p;Heading 1=h1;Heading 2=h2;Heading 3=h3;Heading 4=h4;Heading 5=h5;Heading 6=h6;",
          plugins: 'image table link paste contextmenu textpattern autolink',
        }),
`
但是插件并没有加载。

**Comment by lpreterite** [comment]
最近`tinymce`更新版本后在设置上面有些命名修改了，导致这个插件目前版本的手脚架并不能正常使用，建议你可以按照最新版`tinymce`得例子配置`setting`，应该就能正常运行的了。
