### ISSUE TITLE
spa项目中多个界面加载编辑器，界面切换后刷新后才能输入

### ISSUE THREAD

**Issue by yuhaihui3435** [lpreterite/vue-tinymce#7]
我有两个界面A,B，都分别使用了编辑器组件，当系统第一次调用A的时候，编辑器可用，然后切换到B界面，编辑器无法输入。debug发现，tinymce.init()执行后，editor的init监听，只有页面刷新后的第一次才会执行，类似A界面切换B界面这样的操作，editor不再执行init的监听，请问作者这个问题您遇到了吗，如何解决？急等。

**Comment by lpreterite** [comment]
有具体的代码例子吗？

**Comment by yuhaihui3435** [comment]
有到时候，没法再这上展示啊，使用的就是你组件里的代码。

**Comment by yuhaihui3435** [comment]
`<script>
    import env from '../../../../build/env';
    import kit from '../../../libs/kit';
    import tinymce from 'tinymce';
    import {mapState} from 'vuex'


    const INIT = 0;
    const INPUT = 1;
    const CHANGED = 2;
    export default{
        name: 'my-tinymce',
        computed: {
            ...mapState({
                'uploadPicMaxSize': state => state.uploadPicMaxSize,
            })
        },
        data(){
            return {
                id: 'vue-tinymce-'+Date.now(),
                editor: null,
                status: INIT,
                backup: ''
            }
        },
        props: {
            value: {
                type: String,
                default: ''
            },
            setup: {
                type: Function,
                default: function () {
                }
            },
            setting: {
                type: Object,
                default: function () {

                }
            },
            imgUploadUrl:''

        },
        render(createElement){
            console.info('render')
            return createElement('textarea', {
                attrs: {
                    id: this.id
                }
            });
        },
        watch: {
            value(val){
                if(this.status === CHANGED) return this.status = INPUT;
                if(!this.editor || !this.editor.initialized) return;
                this.editor.setContent(val);
            }
        },
        created(){
            if(typeof tinymce === "undefined") throw new Error('tinymce undefined');
        },
        mounted () {
            console.info(this.id);
            console.info(this.editor);
            let maxSize = this.uploadPicMaxSize;
            let url=this.imgUploadUrl;
            const setting = Object.assign({},
                this.setting,
                {
                    selector: '#'+this.id,
                    setup: (editor)=> {
                        this.setup(editor);
                        this.editor = editor;
                        editor.on('init', ()=>{
                            editor.setContent(this.value);
                            editor.on('input change undo redo execCommand KeyUp', ()=>{
                                if(this.status === INPUT || this.status === INIT) return this.status = CHANGED;
                                this.$emit('input', editor.getContent());
                            });
                            editor.on('NodeChange', ()=>{
                                this.$emit('input', editor.getContent());
                            });
                        });
                    },
                    images_upload_handler: function (blobInfo, success, failure) {
                        if(url==''){
                            failure('没有找到图片上传服务器');
                            return;
                        }
                        if (blobInfo.blob().size > maxSize) {
                            failure('上传的图片过大，图片大小不能超过' + maxSize + 'kb')
                            return;
                        }
                        var xhr, formData;
                        xhr = new XMLHttpRequest();
                        xhr.withCredentials = false;
                        xhr.open('POST', url);
                        xhr.onload = function () {
                            var json;
                            if (xhr.status != 200) {
                                failure('HTTP Error: ' + xhr.status);
                                return;
                            }
                            json = JSON.parse(xhr.responseText);

                            if (!json || typeof json.resData != 'string') {
                                failure('Invalid JSON: ' + xhr.responseText);
                                return;
                            }
                            success(json.resData);
                        };
                        formData = new FormData();
                        formData.append('file', blobInfo.blob(), blobInfo.filename());
                        xhr.send(formData);
                    }
                }
            );
            tinymce.init(setting).then(function(editors) {

            });


        },
        beforeDestroy: function(){
            this.editor.remove();
           tinymce.remove(this.id);
        }
    }
</script>
`

**Comment by yuhaihui3435** [comment]
`<VueTinymce ref="serviceCert" :setting="tinymceCfg" v-model="cardtype.serviceCert" :imgUploadUrl="tinymceImgUploadUrl"></VueTinymce>`
在A中这样引用的

**Comment by yuhaihui3435** [comment]
我感觉好像是 
`this.editor.remove();
tinymce.remove(this.id);`这两句话没起到作用，再不就是用法不对，导致editor在界面切换后不再响应init事件，或者editor认为已经执行过了。具体我不太知道，tinymce没中文文档，真坑。

**Comment by lpreterite** [comment]
tinymce是什么版本？

**Comment by yuhaihui3435** [comment]
4.7.3

**Comment by lpreterite** [comment]
引用方式只是当前引入吗？由于我例子是全局引入处理的，你能提供一下引入的相关配置好让我复现一下环境？

**Comment by MinosIE** [comment]
我也遇到了 同样的问题 请问大神 有什么解决方案吗 @yuhaihui3435 @lpreterite

**Comment by lpreterite** [comment]
> 我也遇到了 同样的问题 请问大神 有什么解决方案吗 @yuhaihui3435 @lpreterite

不清楚具体原因，我没能复现问题，你如果能提供复现代码的话应该能找出问题。
